"""Bond graph construction from residue topology.

Builds per-atom adjacency lists using the residue connectivity table
(``connectivity.json``) generated by ``devtools/scripts/update_connectivity.py``
from the PDB Chemical Component Dictionary.
"""

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

_CONNECTIVITY_FILE = Path(__file__).resolve().parents[1] / "data" / "connectivity.json"
_connectivity_cache: dict = {}

_protein_residues = {
    "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY",
    "HIS", "ILE", "LEU", "LYS", "MET", "PHE", "PRO", "SER",
    "THR", "TRP", "TYR", "VAL",
}
_DNA_residues = {"DA", "DC", "DG", "DT"}
_RNA_residues = {"A", "C", "G", "U"}


def _load_connectivity() -> dict:
    """Load and cache the residue connectivity table."""
    if not _connectivity_cache:
        with open(_CONNECTIVITY_FILE) as f:
            _connectivity_cache.update(json.load(f))
    return _connectivity_cache


def build_bond_graph(scene) -> list:
    """Build per-atom adjacency list from residue topology.

    Parameters
    ----------
    scene : Scene
        Must contain columns ``model``, ``chain``, ``resid``, ``icode``,
        ``name``, and ``resname``.

    Returns
    -------
    list[list[int]]
        ``adj[i]`` contains the DataFrame row-positions bonded to atom *i*.
    """
    conn = _load_connectivity()
    residues_table = conn["residues"]
    protein_link = conn["protein_link"]   # ["C", "N"]
    nucleic_link = conn["nucleic_link"]   # ["O3", "P"]

    n = len(scene)
    adj: list = [[] for _ in range(n)]

    # Normalize atom names: strip primes (PDB uses C1', CIF uses C1)
    norm_name = scene['name'].str.replace("'", "", regex=False)

    # Build lookup: (model, chain, resid, icode, norm_name) → DataFrame position
    atom_lookup: dict = {}
    model_vals = scene['model'].values
    chain_vals = scene['chain'].values
    resid_vals = scene['resid'].values
    icode_vals = scene['icode'].values
    norm_vals = norm_name.values

    for pos in range(n):
        key = (model_vals[pos], chain_vals[pos], resid_vals[pos],
               icode_vals[pos], norm_vals[pos])
        # First atom wins (handles altloc duplicates)
        if key not in atom_lookup:
            atom_lookup[key] = pos

    # Intra-residue bonds
    resname_vals = scene['resname'].values
    # (model, chain, resid, icode, resname) for inter-residue pass
    visited_residues: list = []

    seen_keys: set = set()
    for pos in range(n):
        rkey = (model_vals[pos], chain_vals[pos], resid_vals[pos],
                icode_vals[pos])
        if rkey in seen_keys:
            continue
        seen_keys.add(rkey)
        resname = resname_vals[pos]
        visited_residues.append((*rkey, resname))

        bonds = residues_table.get(resname)
        if bonds is None:
            continue
        model, chain, resid, icode = rkey
        for a1, a2 in bonds:
            k1 = (model, chain, resid, icode, a1)
            k2 = (model, chain, resid, icode, a2)
            i = atom_lookup.get(k1)
            j = atom_lookup.get(k2)
            if i is not None and j is not None and i != j:
                adj[i].append(j)
                adj[j].append(i)

    # Inter-residue bonds: peptide (C→N) and phosphodiester (O3→P)
    protein_set = _protein_residues
    nucleic_set = _DNA_residues | _RNA_residues

    # Group residues by (model, chain), sorted by resid
    chain_residues: dict = defaultdict(list)
    for model, chain, resid, icode, resname in visited_residues:
        chain_residues[(model, chain)].append((resid, icode, resname))

    for (model, chain), res_list in chain_residues.items():
        res_list.sort(key=lambda x: (x[0], x[1]))
        for idx in range(len(res_list) - 1):
            resid_i, icode_i, resname_i = res_list[idx]
            resid_j, icode_j, resname_j = res_list[idx + 1]

            # Peptide bond
            if resname_i in protein_set and resname_j in protein_set:
                link_a, link_b = protein_link
                k1 = (model, chain, resid_i, icode_i, link_a)
                k2 = (model, chain, resid_j, icode_j, link_b)
                i = atom_lookup.get(k1)
                j = atom_lookup.get(k2)
                if i is not None and j is not None:
                    adj[i].append(j)
                    adj[j].append(i)

            # Phosphodiester bond
            if resname_i in nucleic_set and resname_j in nucleic_set:
                link_a, link_b = nucleic_link
                k1 = (model, chain, resid_i, icode_i, link_a)
                k2 = (model, chain, resid_j, icode_j, link_b)
                i = atom_lookup.get(k1)
                j = atom_lookup.get(k2)
                if i is not None and j is not None:
                    adj[i].append(j)
                    adj[j].append(i)

    return adj


def compute_bonds(scene):
    """Add bond-derived columns to a Scene.

    Adds the following columns:

    - ``numbonds`` — number of covalent bonds per atom.
    - ``pfrag`` — connected-component index among protein residues
      (``-1`` for non-protein atoms).
    - ``nfrag`` — connected-component index among nucleic-acid residues
      (``-1`` for non-nucleic atoms).

    The bond adjacency list is stored in ``_meta['bonds']``.

    Parameters
    ----------
    scene : Scene
        Input scene (not modified).

    Returns
    -------
    Scene
        Copy with the new columns.
    """
    out = scene.copy()
    adj = build_bond_graph(out)
    out._meta['bonds'] = adj

    # numbonds
    out['numbonds'] = [len(neighbors) for neighbors in adj]

    # pfrag / nfrag via connected components on residue graph
    protein_set = _protein_residues
    nucleic_set = _DNA_residues | _RNA_residues

    pfrag = np.full(len(out), -1, dtype=int)
    nfrag = np.full(len(out), -1, dtype=int)

    residue_vals = out['residue'].values
    resname_vals = out['resname'].values

    # Map residue index → set of atom positions
    res_atoms: dict = defaultdict(list)
    for pos in range(len(out)):
        res_atoms[residue_vals[pos]].append(pos)

    # Build residue adjacency
    res_neighbors: dict = defaultdict(set)
    for pos, neighbors in enumerate(adj):
        r1 = residue_vals[pos]
        for nb in neighbors:
            r2 = residue_vals[nb]
            if r1 != r2:
                res_neighbors[r1].add(r2)
                res_neighbors[r2].add(r1)

    # Residue → resname (use first atom's resname)
    res_resname: dict = {}
    for pos in range(len(out)):
        r = residue_vals[pos]
        if r not in res_resname:
            res_resname[r] = resname_vals[pos]

    def _connected_components(res_set):
        """BFS to find connected components among residues in *res_set*."""
        visited: set = set()
        components: list = []
        for r in res_set:
            if r in visited:
                continue
            comp: list = []
            queue = [r]
            while queue:
                cur = queue.pop()
                if cur in visited:
                    continue
                visited.add(cur)
                comp.append(cur)
                for nb in res_neighbors.get(cur, []):
                    if nb not in visited and nb in res_set:
                        queue.append(nb)
            components.append(comp)
        return components

    # Protein fragments
    protein_residues = {r for r, rn in res_resname.items() if rn in protein_set}
    for frag_id, comp in enumerate(_connected_components(protein_residues)):
        for r in comp:
            for pos in res_atoms[r]:
                pfrag[pos] = frag_id

    # Nucleic fragments
    nucleic_residues = {r for r, rn in res_resname.items() if rn in nucleic_set}
    for frag_id, comp in enumerate(_connected_components(nucleic_residues)):
        for r in comp:
            for pos in res_atoms[r]:
                nfrag[pos] = frag_id

    out['pfrag'] = pfrag
    out['nfrag'] = nfrag
    return out
