name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macOS-latest
          #- macOS-13
          - ubuntu-latest
          #- ubuntu-24.04-arm
          #- windows-lates
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        numpy-version:
          - "numpy=2"
          - "numpy=1"
        exclude:
          - python-version: "3.13"
            numpy-version: "numpy=1"

    steps:
    - uses: actions/checkout@v4

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        create-args: >-
          python=${{ matrix.python-version }}
          ${{ matrix.numpy-version }}

    - name: Install package
      run: |
        python -m pip install . --no-deps

    - name: Environment Information
      run: |
        micromamba info
        micromamba list

    - name: Run tests
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        pytest -v --cov=molscene --cov-report=xml --color=yes molscene/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
